#!/usr/bin/env bash

while true
do
    # echo ""
    out=$(cat ~/.local/qm/dynamic_out.txt)
    echo "$out"  | jq --unbuffered --compact-output
    # cat ~/.config/hypr/scripts/tools/dynamic_out.txt
    sleep 0.5
done